name: Daily Random Quote Commit (Random Time)

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC, but delay makes it random

  push:
    branches:
      - main  # Runs when you push manually

jobs:
  random_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Introduce Random Delay (0 to 6 hours)
        run: sleep $(( RANDOM % 21600 ))

      - name: Initialize Counter If Missing
        run: |
          if [ ! -f counter.txt ]; then
            echo "0" > counter.txt
          fi

      - name: Read Counter
        id: counter
        run: echo "COUNT=$(cat counter.txt)" >> $GITHUB_ENV

      - name: Stop After 150 Days
        if: ${{ env.COUNT >= 150 }}
        run: echo "Stopping workflow after 150 days" && exit 0

      - name: Add a Random Quote
        run: |
          quotes=("Keep going, you’re doing great!" \
                  "Believe in yourself and your abilities." \
                  "Every day is a new opportunity to grow." \
                  "Success is built on small, consistent efforts." \
                  "Stay positive, work hard, make it happen.")

          selected_quote=${quotes[$RANDOM % ${#quotes[@]}]}
          echo "$(date): $selected_quote" >> daily_quotes.txt

      - name: Update Counter
        run: echo "$(( $COUNT + 1 ))" > counter.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add daily_quotes.txt counter.txt
          git commit -m "Added a new quote - Day $(( $COUNT + 1 ))"
          git push
